version: '3'

services:
  purceddhroxy:
    build: Dockerfile
    volumes:
      - ./filters:/purceddhroxy/filters
    restart: always

  proxy:
    build: .
    command:
      -
    ports:
      - "8080:8080"
    depends_on:
      - purceddhroxy
    restart: always