version: '3'

services:
  djangoapp:
    build: .
    command: "sh ./commands/starter.sh"
    environment:
      - DJANGO_SETTINGS_MODULE=djangoPurceddhroxy.settings
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always

  proxy:
    build: .
    privileged: true
    network_mode: "host"
    command: "sh ./commands/iptablesSetup.sh"
    environment:
      - DJANGO_WS_URL=ws://django:8000/ws/packets/
    depends_on:
      - djangoapp